name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-and-lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift 6.1
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.1"
      - name: Verify formatting
        run: |
          swift format --version
          swift format --lint Sources Tests Examples
      - name: Swift package diagnostics
        run: swift package diagnose

  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, ubuntu-22.04]
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift 6.1
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "6.1"
      - name: Display Swift version
        run: swift --version
      - name: Build package
        run: swift build --build-tests
      - name: Run tests
        run: swift test --parallel
